#!/usr/bin/env bun
// ABOUTME: Dev script that regenerates registry.json and src/index.ts from component source files.
// ABOUTME: Invoked automatically by the pre-commit git hook — do not need to run manually.

import { readdir, readFile } from "fs/promises";
import { join } from "path";

const SRC_DIR = "./src";
const EXCLUDE = new Set(["index.ts"]);
const PEER_DEPS = new Set(["react", "react-dom"]);
const INTERNAL_PREFIXES = [".", "/", "@/", "node:", "bun:"];

function extractDeps(source) {
  const deps = new Set();
  for (const [, pkg] of source.matchAll(/^import .+ from ['"]([^'"]+)['"]/gm)) {
    if (INTERNAL_PREFIXES.some(p => pkg.startsWith(p))) continue;
    if (PEER_DEPS.has(pkg) || pkg.startsWith("react/")) continue;
    const name = pkg.startsWith("@")
      ? pkg.split("/").slice(0, 2).join("/")
      : pkg.split("/")[0];
    deps.add(name);
  }
  return [...deps];
}

const files = (await readdir(SRC_DIR))
  .filter(f => (f.endsWith(".tsx") || f.endsWith(".ts")) && !EXCLUDE.has(f))
  .sort();

const components = {};
const exports = [];

for (const file of files) {
  const name = file.replace(/\.tsx?$/, "");
  const source = await readFile(join(SRC_DIR, file), "utf8");
  const descMatch = source.match(/\/\/ ABOUTME: (.+)/);
  components[name] = {
    description: descMatch ? descMatch[1] : name,
    files: [`src/${file}`],
    dependencies: extractDeps(source),
  };
  exports.push(`export * from "./${name}";`);
}

await Bun.write("registry.json", JSON.stringify({ components }, null, 2) + "\n");
await Bun.write("src/index.ts", [
  "// ABOUTME: Central export file for all forge components.",
  "// ABOUTME: Auto-generated by the pre-commit hook — do not edit by hand.",
  "",
  ...exports,
  "",
].join("\n"));

console.log(`Synced: ${files.map(f => f.replace(/\.tsx?$/, "")).join(", ")}`);
